### ISSUE TITLE
Travian Resource Bar Plus / Travian Task Queue

### ISSUE THREAD

**Issue by 0Fud** [adipiciu/Travian-scripts#76]
**Script Name**
Travian Resource Bar Plus & Travian Task Queue 

**Travian Server address**
america.travian.com

**Browser**
Brave/chrome

**User script manager**
Violentmonkey

**Operating System**
 Windows, iOS

**Describe the bug**

Travian Task Queue for Travian 4.user.js:72 Uncaught TypeError: Cannot read properties of null (reading 'getElementsByClassName')
    at $gc (Travian Task Queue for Travian 4.user.js:72:69)
    at vlist_addButtonsT4 (Travian Task Queue for Travian 4.user.js:689:17)
    at allInOneTTQ (Travian Task Queue for Travian 4.user.js:746:2)
    at Travian Task Queue for Travian 4.user.js:4167:41
    at Travian Task Queue for Travian 4.user.js:4171:3
    at VMrokc7xla7f (Travian Task Queue for Travian 4.user.js:4172:3)
    at rn (injected-web.js:1:15900)
    at Travian Task Queue for Travian 4.user.js:1:20
    at async Wt (injected.js:1:8803)
    at async injected.js:1:14545
$gc @ Travian Task Queue for Travian 4.user.js:72
vlist_addButtonsT4 @ Travian Task Queue for Travian 4.user.js:689
allInOneTTQ @ Travian Task Queue for Travian 4.user.js:746
(anonymous) @ Travian Task Queue for Travian 4.user.js:4167
(anonymous) @ Travian Task Queue for Travian 4.user.js:4171
VMrokc7xla7f @ Travian Task Queue for Travian 4.user.js:4172
rn @ injected-web.js:1
(anonymous) @ Travian Task Queue for Travian 4.user.js:1
await in (anonymous)
zt @ injected.js:1
Wt @ injected.js:1
await in Wt
(anonymous) @ injected.js:1
await in (anonymous)
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
Show 5 more frames

Travian Resource bar plus.user.js:2590 Uncaught TypeError: Cannot read properties of null (reading 'getElementsByClassName')
    at $gc (Travian Resource bar plus.user.js:2590:69)
    at vlist_addButtonsT4 (Travian Resource bar plus.user.js:4630:17)
    at allInOneOpera (Travian Resource bar plus.user.js:9204:2)
    at Travian Resource bar plus.user.js:9301:42
    at Travian Resource bar plus.user.js:9305:3
    at VMnk635j0je2 (Travian Resource bar plus.user.js:9306:3)
    at rn (injected-web.js:1:15900)
    at Travian Resource bar plus.user.js:1:20
    at async Wt (injected.js:1:8803)
    at async injected.js:1:14545

**Comment by adipiciu** [comment]
Fixed. Thanks for reporting.
